### ISSUE TITLE
SCD30-CLI bus number option error (Invalid I2C bus number NaN)

### ISSUE THREAD

**Issue by BrianDee67** [rsmeral/scd30-cli#2]
Hi

I have 2 x SCD30 sensors on separate I2C busses due to not being able to change the sensors address (hardware set permanently at 0x61).
I have added 2 new busses at /dev/i2c-3 & /dev/i2c-4
```
 ~$ sudo i2cdetect -y -l
      i2c-3   i2c             3.i2c                                         I2C adapter
      i2c-1   i2c             bcm2835 (i2c@7e804000)       I2C adapter
      i2c-4   i2c             4.i2c                                         I2C adapter
```

They both return addresses successfully

```
pi@mypi:~$ sudo i2cdetect -y 3
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- 61 -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --
```
```
pi@mypi:~$ sudo i2cdetect -y 4
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- 61 -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --
```

However I can't connect to either of then via the scd30-cli to alter any configuration parameters as the command line bus number option always returns error as below:

```
pi@mypi:~$ scd30-cli -b 3 status
(node:1197) UnhandledPromiseRejectionWarning: Error: **Invalid I2C bus number NaN**
    at checkBusNumber (/usr/local/share/.config/yarn/global/node_modules/i2c-bus/i2c-bus.js:61:11)
    at open (/usr/local/share/.config/yarn/global/node_modules/i2c-bus/i2c-bus.js:35:3)
    at /usr/local/share/.config/yarn/global/node_modules/i2c-bus/i2c-bus.js:53:17
    at new Promise (<anonymous>)
    at Object.openPromisified (/usr/local/share/.config/yarn/global/node_modules/i2c-bus/i2c-bus.js:51:49)
    at /usr/local/share/.config/yarn/global/node_modules/scd30-node/dist/index.js:227:33
    at Generator.next (<anonymous>)
    at /usr/local/share/.config/yarn/global/node_modules/scd30-node/dist/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/share/.config/yarn/global/node_modules/scd30-node/dist/index.js:4:12)
(node:1197) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1197) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Same error for bus number 4

Is this a bug or am I providing the bus number in the wrong format?

**Comment by rsmeral** [comment]
Ah, I had a silly bug in option parsing. Sorry!
Just published version 1.0.2 –  should work now.

**Comment by BrianDee67** [comment]
Thanks for updating the code, however I am still seeing the same error.

`pi@b-sharpe-pi:~$ yarn global add scd30-cli
yarn global v1.22.10
warning package.json: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "scd30-cli@1.0.2" with binaries:
      - scd30-cli
Done in 3.13s.
pi@b-sharpe-pi:~$ sudo scd30-cli -b 3 status
(node:2863) UnhandledPromiseRejectionWarning: Error: Invalid I2C bus number NaN
    at checkBusNumber (/usr/local/share/.config/yarn/global/node_modules/i2c-bus/i2c-bus.js:61:11)
    at open (/usr/local/share/.config/yarn/global/node_modules/i2c-bus/i2c-bus.js:35:3)
    at /usr/local/share/.config/yarn/global/node_modules/i2c-bus/i2c-bus.js:53:17
    at new Promise (<anonymous>)
    at Object.openPromisified (/usr/local/share/.config/yarn/global/node_modules/i2c-bus/i2c-bus.js:51:49)
    at /usr/local/share/.config/yarn/global/node_modules/scd30-node/dist/index.js:227:33
    at Generator.next (<anonymous>)
    at /usr/local/share/.config/yarn/global/node_modules/scd30-node/dist/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/share/.config/yarn/global/node_modules/scd30-node/dist/index.js:4:12)
(node:2863) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:2863) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
pi@b-sharpe-pi:~$
`

I tried both with sudo and without but no change.

**Comment by rsmeral** [comment]
I'm pretty sure you're still seeing the bug because of some Yarn caching issue.
Try reinstalling the package – `yarn global remove scd30-cli`, then `yarn global add scd30-cli`.

Alternatively, you can install it globally also using npm:
`npm i -g scd30-cli`

You can also run the package using `npx` without installing it (though this is very slow as it fetches dependencies on each run):
`npx scd30-cli`
